language: go
go:
  - 1.13.x
env:
  - GO111MODULE=on

git:
  depth: 1

notifications:
  email: true

script:
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)